#!/usr/bin/expect -f

set script  [lindex $argv 0]
set usuario [lindex $argv 1]
set dominio [lindex $argv 2]
set puerto  [lindex $argv 3]
set pass    [lindex $argv 4]

set force_conservative 0
if {$force_conservative} {
    set send_slow {1 .1}
    proc send {ignore arg} {
	sleep .1
	exp_send -s -- $arg
    }
}
set timeout -1
spawn "$script" $usuario $dominio $puerto
match_max 100000
expect -re "password:"
send -- "$pass\r"
expect -re "sudo"
send -- "$pass\r"
expect eof
